package es.universidad.pfg.controlador;



import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;



//@Controller    // This means that this class is a Controller
//@RequestMapping(path="/piso") // This means URL's start with /demo (after Application path)
public class PisoController {
//	@Autowired // This means to get the bean called userRepository
//	           // Which is auto-generated by Spring, we will use it to handle the data
//	private PisoDao pisoDao;
//	
//	@GetMapping(path="/add") // Map ONLY GET Requests
//	public @ResponseBody String addNewPiso (@RequestParam String nombre
//			, @RequestParam String correo, @RequestParam String apellido_1, @RequestParam String apellido_2) {
//		// @ResponseBody means the returned String is the response, not a view name
//		// @RequestParam means it is a parameter from the GET or POST request
//		
//		Piso n = new Piso();
//		n.setLocality(nombre);
//		n.setNumber(apellido_1);
//		pisoDao.save(n);
//		return "Saved";
//	}
//	
//	@GetMapping(path="/all")
//	public @ResponseBody Iterable<Piso> getAllPisos() {
//		// This returns a JSON or XML with the users
//		return pisoDao.findAll();
//	}
}
